services:
  schedy-nginx:
    image: schedy-nginx
    container_name: schedy-nginx
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_completed_successfully

  database:
    image: schedy-postgres
    container_name: schedy-pg
    ports:
      - "5432:5432"
    volumes:
      - "/data"

  seapig-server:
    image: schedy-server-devel
    container_name: schedy-seapig-server
    command: seapig-server --disable-json-diff
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_completed_successfully

  seapig-worker:
    image: schedy-server-devel
    environment:
      RAILS_ENV=production
    command: seapig-worker
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      database:
        condition: service_completed_successfully
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: a86416f38d79d6c8d8c58d030f9df72a418cb7574f3c6f5b15a7a0140fc0e41aee8a38a907fdacc59a57f3d03c028addd16d1e0b206aabae83c6d25a89177502

  schedy-router:
    image: schedy-server-devel
    container_name: schedy-router
    command: seapig-router-session-manager
    depends_on:
      database:
        condition: service_completed_successfully

  schedy-status-saver:
    image: schedy-server-devel
    container_name: schedy-status-saver
    command: ruby bin/worker-status-saver http://127.0.0.1:3001/seapig
    depends_on:
      database:
        condition: service_completed_successfully

  seapig-notifier:
    image: schedy-server-devel
    container_name: schedy-seapig-notifier
    command: seapig-postgresql-notifier
    depends_on:
      database:
        condition: service_completed_successfully

  schedy-dealer:
    image: schedy-server-devel
    container_name: schedy-dealer
    command: ruby bin/dealer http://127.0.0.1:3001/seapig http://127.0.0.1:3000/
    depends_on:
      database:
        condition: service_completed_successfully

  rails:
    image: schedy-server-devel
    container_name: schedy-server-rails
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: a86416f38d79d6c8d8c58d030f9df72a418cb7574f3c6f5b15a7a0140fc0e41aee8a38a907fdacc59a57f3d03c028addd16d1e0b206aabae83c6d25a89177502
    command: rails server -p 3100
    ports:
      - "3100:3100"
    depends_on:
      database:
        condition: service_completed_successfully"
