source 'https://rubygems.org'

gem 'munkres'
gem 'rest-client'
gem 'rspec'
gem 'ruby-prof'
gem 'websocket-eventmachine-client'
gem 'hana'
gem 'activerecord'
gem 'jsondiff'
gem 'httpclient'
gem 'seapig-client'
gem 'pg'
gem 'daemons'
gem 'awesome_print'
gem 'rake'
